# Author: Andrés Quesada
# Course: Desarrollo de sistemas empotrados en C y Linux

all: main.c main.h programa1.c programa1.h
	gcc -o programa1 programa1.c
	gcc -o programa2 main.c

clean:
	rm -fr programa2
	rm -fr programa1
